### ISSUE TITLE
Disabling all Q.E.D. symbols

### ISSUE THREAD

**Issue by hiorig** [Jinwen-XU/homework#3]
Is there a quick way to disable all Q.E.D. symbols, even on answers/solutions environments? I thought the remove qed option in the beginning of the file would do this, but it works for theorem-like environments only.

I'm using this package to write my Chinese homework and the Q.E.D. symbol has no meaning in this context.

**Comment by Jinwen-XU** [comment]
For some reason I forgot to make this an option, my apologies. In the next version I shall change this option `remove qed` to remove all the Q.E.D. symbols, and add two new options `remove question qed` and `remove answer qed` for switching them off separately.

---

As a temporary solution, before the next update, you could get a copy of `homework.cls` into your working folder, and comment/remove the following two lines:
```latex
\pushQED{\qed}
\popQED\endtrivlist\@endpefalse
```
in the definition of the environment `solution`, like this:

<img width="660" alt="image" src="https://github.com/user-attachments/assets/dc73d4e7-ffdc-4488-85a7-70ec0daebe46">

The Q.E.D. symbols should then be gone after a recompilation.

**Comment by Jinwen-XU** [comment]
Sorry for the delay. The new options are added in Update 2024-09-30 (b90068ac23194eab46de14269fa6a6c9bee851d2), and the corresponding update on CTAN should be available by tomorrow.

If you encounter any further issue, feel free to continue the discussion in this channel or open a new GitHub Issue.
